[package]
name = "genepa_rs"
version = "0.1.0"
authors = ["Marc AndrÃ© Legault <legaultmarc@gmail.com>"]
edition = "2018"

[lib]
name = "rsgeneparselib"
crate-type = ["dylib", "rlib"]

[dependencies]
ndarray = "0.12.1"